#Workflow for test environment

name: test-CI

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build-dev
      - name: Upload project artifacts
        uses: actions/upload-artifact@v2
        with:
          path: dist/
          name: project

  deploy-test:
    # if: contains( github.ref, 'develop')
    needs: build
    runs-on: ubuntu-latest
    container: alexsuch/angular-cli:7.3.8
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test.yml
          workflow_conclusion: success
          name: project
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DROPLET_KEY }}
          known_hosts: ${{ secrets.DROPLET_HOST }}
      - name: Deploy with rsync
        run: |
          echo $DROPLET_ENV | base64 -d > .env
          rsync -zhrl -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' . $SSH_USER@$SSH_HOST:$PROJECT_PATH
        env:
          SSH_USER: ${{ secrets.DROPLET_USER }}
          SSH_HOST: ${{ secrets.DROPLET_HOST }}
          PROJECT_PATH: ${{ secrets.DROPLET_CMS_DEMO_PATH }}
          DROPLET_ENV: ${{ secrets.DROPLET_CMS_DEMO_DOTENV_BASE64 }}